site_name: IITM Notes
theme: 
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - toc.float

  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: magenta
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to Light Mode
      primary: magenta
      accent: lime

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - Home : "index.md"
  - Foundational 2:
    - Stats2:
      - Week 1:
        - Discrete Random Variables : "STATS2/WEEK 1/Notes/Two Discrete Random Variables.md"
        - AQ Solutions : "STATS2/WEEK 1/aq_solutions.md"
      - Week 2:
        - Independent Random Variables : "STATS2/WEEK 2/Notes/Notes.md"
        - Extra Useful Content : "STATS2/WEEK 2/Notes/Extra Content.md"
        - AQ Solutions : "STATS2/WEEK 2/AQ Solutions.md"
      - Week 3:
        - Expectation of Random Variables: "STATS2/WEEK 3/Expectation of Random Variables.md"
        - AQ Solutions : "STATS2/WEEK 3/AQ Solutions.md"
      - Week 4:
        - Continuous Random Variables: "STATS2/WEEK 4/Continuous Random Variables.md"

    - Maths2:
      - Week 1:
        - Vectors and Matrices : "MATHS2/1.02 - Matricies.md"
        - Determinants : "MATHS2/1.03 - Determinants.md"
      - Week 2:
        - Cramer's Rule : "MATHS2/2.01 - Cramer's Rule.md"
        - Invertible Coefficient Matrix: "MATHS2/2.02 - Solutions to a system of linear equations with invertible coefficient.md"
        - Echelon Form : "MATHS2/2.03 - The Echelon form.md"
        - Row Reduction : "MATHS2/2.04 - Row Reduction.md"
        - Gaussian Elimination : "MATHS2/2.05 - Gaussian elemination.md"
      - Week 3:
        - Vector Spaces : "MATHS2/3.01 - Vector Spaces.md"
      - Week 4:
        - Vector Basis: "MATHS2/4.01 - Vector Basis.md"


  - DS Diploma:
    - Machine Learning Foundations:
      - Week 3:
        - Four Fundamental Subspaces: "MLF/WEEK 3/Four Fundamental Subspaces.md"
    - Business Data Management:
      - Week 1: "BDM/WEEK 1/Consumption.md"
      - Week 2: 
        - Consumer Behaviour : "BDM/WEEK 2/Consumer Behaviour.md"
        - Markets and Competiton : "BDM/WEEK 2/Markets and Competiton.md"
        - Elasticity and Demand : "BDM/WEEK 2/Elasticity and Demand.md"
        - Production Cost : "BDM/WEEK 2/Production Cost.md"
        - Cost Curves : "BDM/WEEK 2/Cost Curves.md"
        - Make vs. Buy : "BDM/WEEK 2/Make Buy.md"
        - Production Decisions : "BDM/WEEK 2/Production Decisions.md"
      - Week 3:
        - Pricing Strategies : "BDM/WEEK 3/Pricing Strategies.md"
        - Analysis of Firm Performance : "BDM/WEEK 3/Analysis of Firm Performance.md"
      - Week 4:
        - Industry Definition : "BDM/WEEK 4/Industry Definition.md"
        
# REPO CONFIG
repo_url : "https://github.com/Javets70/iitm_notes"
repo_name : "Javets70/iitm_notes"

extra:
  social:
    - icon : material/github
      link : https://github.com/kabironline/IIT-notes
      name : Maths2 Notes Contributor
      title : Hello
# EXTENSIONS AND CSS
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css


    

