site_name: IITM Notes
theme: 
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - toc.float

  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: magenta
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to Light Mode
      primary: magenta
      accent: lime

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - Home : "index.md"
  - Foundational 2:
    - Stats2:
      - Week 1:
        - Discrete Random Variables : "STATS2/WEEK 1/Notes/Two Discrete Random Variables.md"
        - AQ Solutions : "STATS2/WEEK 1/aq_solutions.md"
      - Week 2:
        - Independent Random Variables : "STATS2/WEEK 2/Notes/Notes.md"
        - Extra Useful Content : "STATS2/WEEK 2/Notes/Extra Content.md"
        - AQ Solutions : "STATS2/WEEK 2/AQ Solutions.md"
      - Week 3:
        - Expectation of Random Variables: "STATS2/WEEK 3/Expectation of Random Variables.md"
        - AQ Solutions : "STATS2/WEEK 3/AQ Solutions.md"
      - Week 4:
        - Continuous Random Variables: "STATS2/WEEK 4/Continuous Random Variables.md"
        - AQ Solutions: "STATS2/WEEK 4/AQ Solutions.md"
      - Week 5:
        - Functions of Continuous Random Variables: "STATS2/WEEK 5/Functions of Continuous Random Variables.md"
        - AQ Solutions: "STATS2/WEEK 5/AQ Solutions.md"
      - Week 6:
        - Joint Continuous Random Variables: "STATS2/WEEK 6/Joint Continuous Random Variables.md"
        - AQ Solutions: "STATS2/WEEK 6/AQ Solutions.md"
      - Week 7:
        - Empirical Distributions and Descriptive Statistics: "STATS2/WEEK 7/Empirical Distribution and Descriptive Statistics.md"
      - Week 8:
        - Central Limit Theorem : "STATS2/WEEK 8/Central Limit Theorem.md" 
        - AQ Solutions: "STATS2/WEEK 8/AQ Solutions.md"
      - Week 9:
        - Parameter Estimation: "STATS2/WEEK 9/Parameter Estimation.md"


    - Maths2:
      - Week 1:
        - Vectors and Matrices : "MATHS2/1.02 - Matricies.md"
        - Determinants : "MATHS2/1.03 - Determinants.md"
      - Week 2:
        - Cramer's Rule : "MATHS2/2.01 - Cramer's Rule.md"
        - Invertible Coefficient Matrix: "MATHS2/2.02 - Solutions to a system of linear equations with invertible coefficient.md"
        - Echelon Form : "MATHS2/2.03 - The Echelon form.md"
        - Row Reduction : "MATHS2/2.04 - Row Reduction.md"
        - Gaussian Elimination : "MATHS2/2.05 - Gaussian elemination.md"
      - Week 3:
        - Vector Spaces : "MATHS2/3.01 - Vector Spaces.md"
      - Week 4:
        - Vector Basis: "MATHS2/4.01 - Vector Basis.md"
      - Week 5:
        - Nullspace and Nullity: "MATHS2/5.01 - null space and nullity.md"


  - DS Diploma:
    - Machine Learning Foundations:
      - Week 3:
        - Four Fundamental Subspaces: "MLF/WEEK 3/Four Fundamental Subspaces.md"
      - Linear Algebra and Its Applications (Solutions):
        - Whats this for? : "MLF/G Strang Solutions/Introduction.md"
        - Matrices and Gaussian Elimination (Chapter 1) : "MLF/G Strang Solutions/Chapter 1.md"

    - Machine Learning Techniques:
      - Week 1:
        - Representation Learning: "MLT/WEEK 1/Representation Learning.md"
      - Week 2:
        - Kernel PCA: "MLT/WEEK 2/Kernel PCA.md" 
      - Week 3:
        - Clustering: "MLT/WEEK 3/Clustering.md"
      - Week 4:
        - Estimation: "MLT/WEEK 4/Estimation.md"
      - Week 5:
        - Supervised Learning : "MLT/WEEK 5/Supervised Learning.md"
      - Week 6:
        - Regression: "MLT/WEEK 6/Regression.md"

    - Business Data Management:
      - Week 1: "BDM/WEEK 1/Consumption.md"
      - Week 2: 
        - Consumer Behaviour : "BDM/WEEK 2/Consumer Behaviour.md"
        - Markets and Competiton : "BDM/WEEK 2/Markets and Competiton.md"
        - Elasticity and Demand : "BDM/WEEK 2/Elasticity and Demand.md"
        - Production Cost : "BDM/WEEK 2/Production Cost.md"
        - Cost Curves : "BDM/WEEK 2/Cost Curves.md"
        - Make vs. Buy : "BDM/WEEK 2/Make Buy.md"
        - Production Decisions : "BDM/WEEK 2/Production Decisions.md"
      - Week 3:
        - Pricing Strategies : "BDM/WEEK 3/Pricing Strategies.md"
        - Analysis of Firm Performance : "BDM/WEEK 3/Analysis of Firm Performance.md"
      - Week 4:
        - Industry Definition : "BDM/WEEK 4/Industry Definition.md"
        
# REPO CONFIG
repo_url : "https://github.com/Javets70/iitm_notes"
repo_name : "Javets70/iitm_notes"

extra:
  social:
    - icon : material/github
      link : https://github.com/kabironline/IIT-notes
      name : Maths2 Notes Contributor
      title : Hello


# EXTENSIONS AND CSS
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css


