site_name: IITM Notes
theme: 
  name: material
  features:
    - search
    - navigation.tabs
    - toc.float
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - Foundational 2:
    - Stats2:
      - Week 1:
        - Discrete Random Variables : "STATS2/WEEK 1/Notes/Two Discrete Random Variables.md"
        - AQ Solutions : "STATS2/WEEK 1/aq_solutions.md"
      - Week 2:
        - Independent Random Variables : "STATS2/WEEK 2/Notes/Notes.md"



markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


    

